site_name: NICD Wastewater Genomics Syndicate 
nav: 
  - Home: index.md 
  - "Sample Maps": sample_maps.md
  - "Turnaround Times": labtat.md
  - "Sequencing Analysis": sequencing.md
  - "SARS-CoV-2 Quantitative Levels": quantitative.md
  - "Influenza Analysis": influenza.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: light green
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: light green
      accent: lime
markdown_extensions:
- attr_list


copyright: Copyright (c) 2024, NICD-Wastewater-Genomics
